export const all_recipes = [
  {
    id: "1",
    name: "Classic Cheesecake",
    category: "cakes",
    time: "April 19, 2021",
    author: " by Irina Stasii | You Can Bake It! ",
    keywords: [
      "eggs",
      "sugar",
      "baking",
      "heavy cream",
      "butter",
      "digestive biscuits",
      "cheesecake",
      "classic cheesecake",
      "baked cheesecake",
      "cream cheese",
    ],
    description:
      "Classic baked cheesecake is a timeless dessert that epitomizes indulgence and satisfaction. This heavenly treat features a smooth, creamy texture with a rich, decadent flavor profile. The foundation of this dessert is a buttery graham cracker crust that perfectly complements the velvety filling. The cheesecake filling, made from a blend of cream cheese, sugar, and eggs, is baked to perfection, resulting in a dense and luxurious consistency. The gentle baking process allows the flavors to meld, creating a harmonious balance that's both creamy and slightly tangy. Topped with a simple yet elegant finish, like a drizzle of fruit compote or a dusting of powdered sugar, the classic baked cheesecake is a showstopper on any dessert table. Whether enjoyed on its own or paired with your favorite toppings, this timeless dessert is a celebration of culinary craftsmanship, delivering pure delight in every forkful. Perfect for gatherings or as a comforting treat, the classic baked cheesecake is an enduring symbol of sweet indulgence.",
    image: "./cakes_img/ClassicCheesecake.jpg",
    recipe_part1: "Crust",
    ingredients_part1: ["300g digestive biscuits", "75g butter"],
    instructions1:
      "Finely crush the biscuits.Melt the butter and add it to the biscuits. Mix the composition well and form the crust in the pan. I flatten it with my hands and then with a spoon. Cover the edges of the pan with aluminum foil in multiple layers as the pan will be placed in water. Place the pan in a preheated oven at 150°C for 10 minutes, and in the meantime, work on the filling. ",
    recipe_part2: "Filling",
    ingredients_part2: [
      "600g cream cheese",
      "150g sugar",
      "1 tablespoon cornstarch",
      "4 eggs (M)",
      "Vanilla",
      "1 tablespoon lemon juice",
      "110g heavy cream",
    ],
    instructions2:
      "Use a whisk to mix the cream cheese, sugar, and cornstarch. Add the eggs one by one, mixing after each one. Add the remaining ingredients and mix until the composition is homogeneous.❗ Do not mix too much, only as much as necessary to homogenize the composition. In the oven pan, pour hot water. Set the oven to 140°C. Pour the cheesecake filling over the biscuit crust and place the cheesecake pan in the pan with hot water in the oven. Bake the cheesecake for 80 minutes without ventilation. Place the pan on the 3rd rack of the oven, not the lowest one. When the time has elapsed, turn off the oven, remove the cheesecake pan from the water bath (we no longer need the water pan, so remove it from the oven), and let the cheesecake cool in the oven with the door slightly open for 1-2 hours.",
    observations:
      "It is important that the cheesecake is refrigerated for a minimum of 8 hours after it has completely cooled in the oven.",
  },
  {
    id: "2",
    name: "Chocolate Caramel Mousse with peanuts",
    category: "cakes",
    time: "October 30, 2020",
    author: " by Irina Stasii | You Can Bake It!",
    keywords: [
      "cake",
      "mousse cake",
      "mousse",
      "caramel",
      "chocolate",
      "Chocolate sponge",
      "Caramel insert",
      "Chocolate mousse",
      "Eggs",
      "Sugar",
      "Baking",
      "Heavy cream",
      "peanuts",
      "Butter",
      "Chocolate",
      "peanuts",
    ],
    description:
      "Indulge in the decadent harmony of flavors with this Chocolate Mousse Cake. This exquisite dessert features layers of velvety chocolate sponge cake, generously filled with luscious chocolate mousse that melts in your mouth. As you delve deeper, you'll discover a delightful surprise—an irresistibly gooey caramel center that adds a perfect balance of sweetness. Every forkful is a symphony of rich chocolate and silky caramel, creating a luxurious treat that's sure to captivate your taste buds and leave you craving more. Elevate your dessert experience with this delightful combination of textures and flavors in our Chocolate Mousse Cake.",
    image: "./cakes_img/CaramelMousse1.jpg",
    image2: "./cakes_img/CaramelMousse2.jpg",
    recipe_part1: "Please visit Instagram post for this recipe.",
    instaLink: "https://www.instagram.com/p/CHSMJnvptN3/?img_index=1",
    ingredients_part1: [],
    instructions1: "",
    ingredients_part2: [],
    instructions2: "",
    observations: "",
  },
  {
    id: "3",
    name: "Red Velvet Mini Cakes",
    category: "cakes",
    time: "February 23, 2021",
    author: " by Irina Stasii | You Can Bake It!",
    keywords: [
      "cake",
      "mini cakes",
      "cakes",
      "mascarpone",
      "chocolate",
      "strawberry",
      "red cake",
      "sponge",
      "Eggs",
      "Sugar",
      "Baking",
      "Heavy cream",
      "Butter",
      "red velvet",
      "red velvet cake",
    ],
    description:
      "Red velvet mini cakes with strawberry cream are delightful, bite-sized treats that combine the rich, cocoa-flavored goodness of red velvet cake with the luscious sweetness of strawberry cream. These miniature cakes are typically characterized by their vibrant red color and velvety texture. The red velvet layers are often sandwiched together with a sumptuous strawberry cream filling, creating a perfect balance of flavors. The result is a charming dessert that not only captivates the eyes with its appealing appearance but also satisfies the taste buds with a delightful blend of chocolate and fruity sweetness in every bite. These mini cakes are perfect for special occasions, gatherings, or whenever you crave a small, indulgent treat.",
    image: "./cakes_img/MiniRV1.jpg",
    image2: "./cakes_img/MiniRV2.jpg",
    // image3: "./public/cakes_img/MiniRV3.jpg",
    recipe_part1: "Sponge",
    ingredients_part1: [
      "125g soft butter",
      "250g sugar",
      "2 eggs",
      "1 teaspoon vanilla paste/essence",
      "250g flour",
      "1 tablespoon cocoa",
      "A pinch of salt",
      "1 teaspoon baking powder",
      "1 teaspoon baking soda",
      "red food coloring",
      "240g buttermilk",
    ],
    instructions1:
      "Combine buttermilk with baking soda. In a separate bowl, combine the dry ingredients (flour, cocoa, salt, baking powder, food coloring). Mix well with a whisk. In a separate large bowl, beat the soft butter and sugar for 2-3 minutes. Add the eggs and vanilla and mix until incorporated. Add half of the dry ingredients, mix. Add buttermilk, mix. Add the remaining half of the dry ingredients. Spread the mixture as evenly as possible on a baking tray lined with parchment paper (a standard oven tray of 40/42cm is perfect in size). Bake for 25 minutes at 170⁰C (it may take longer, depending on the oven). Cut when it has completely cooled.",
    recipe_part2: "Strawberry cream:",
    ingredients_part2: [
      "375g mascarpone",
      "450g frozen strawberries",
      "75g granulated sugar",
      "600g heavy cream (min. 35% fat)",
      "150g powdered sugar",
      "1 tablespoon lemon juice",
    ],
    instructions2:
      "For strawberry cream we need to put the strawberries and granulated sugar on low heat until the sugar is melted and the strawberries are soft. Blend the mixture with a stick blender. Melt the chocolate (in a double boiler or in the microwave in 20-second intervals, stirring frequently). Whip (not too dense) the heavy cream with powdered sugar. Add lemon juice and mix. Mix the melted (not hot) chocolate with mascarpone. Add the whipped cream and mix with a whisk. Add the strawberry mixture (cold) and mix. Refrigerate the cream for 30 minutes. My mini cakes had 2 layers of cream and 2 layers of cake. I placed crunchy chocolate balls inside.",
    observations: "I assure you they are super tasty! 🥰",
  },
  {
    id: "4",
    name: "Red Velvet Cupcakes",
    category: "",
    time: "February 8, 2021",
    author: " by Irina Stasii | You Can Bake It!",
    keywords: [
      "cupcakes",
      "mascarpone",
      "red cupcakes",
      "sponge",
      "Eggs",
      "Sugar",
      "Baking",
      "Heavy cream",
      "Butter",
      "red velvet",
      "red velvet cupcakes",
      "Valentine's day",
    ],
    description:
      "Picture this: irresistibly moist red velvet cupcakes topped with a smooth, creamy mascarpone frosting. It's like a delicious blend of rich cocoa flavor meets the perfect creamy finish. They're a fancy twist on the classic cupcake, perfect for any sweet tooth craving something a bit special.",
    image: "./otherRecipesImg/RVcupcakes1.jpg",
    image2: "./otherRecipesImg/RVcupcakes2.jpg",
    // image3: "./cakes_img/MiniRV3.jpg",
    recipe_part1: "Cupcakes",
    ingredients_part1: [
      "100g sugar",
      "2 eggs",
      "100g milk",
      "100g melted butter",
      "150g flour",
      "A pinch of salt",
      "30g cocoa powder",
      "7g baking soda",
      "red food coloring",
    ],
    instructions1:
      "With a mixer or whisk, blend the sugar with the eggs until slightly lighter in color. Add the milk + melted butter + food coloring (if it's liquid). Combine flour, cocoa powder, salt, food coloring (if it's powder), and baking soda in a separate bowl, then add to the mixture. Place cupcake liners in a tray (you can also use silicone cupcake molds) and divide the mixture into 12 portions. Bake the cupcakes in a preheated oven at 180°C for 20-23 minutes without ventilation, using the middle rack (check with a toothpick for doneness before removing the tray from the oven).Crush and dry 2 cupcakes in the oven (5-7 minutes at 150-160°C) to obtain red crumbs sprinkled over the cream.",
    recipe_part2: "Mascarpone cream:",
    ingredients_part2: [
      "150g mascarpone",
      "200g heavy cream (min. 35% fat)",
      "40g powdered sugar",
    ],
    instructions2:
      "Mix all the ingredients until the cream thickens. Once the cupcakes are cool, decorate them with the cream and sprinkle the red crumbs on top.",
    observations: "",
  },

  {
    id: "5",
    name: "Pavlova",
    category: "cakes",
    time: "February 6, 2021",
    author: " by Irina Stasii | You Can Bake It!",
    keywords: [
      "cake",
      "meringue",
      "pavlova",
      "sour cream",
      "fruits",
      "pavlova cake",
      "Eggs",
      "Sugar",
      "Baking",
      "Heavy cream",
      "egg whites",
      "powdered sugar",
      "mascarpone",
      "christmas",
    ],
    description:
      "Pavlova is a popular dessert that originated in either Australia or New Zealand (there is ongoing debate about its exact origin). Named after the Russian ballerina Anna Pavlova, it is a meringue-based cake with a crisp crust and a soft, light interior. The meringue is made from egg whites, sugar, and vinegar, which contributes to its unique texture. The combination of the crunchy meringue and the creamy topping creates a delightful contrast in both texture and flavor, making Pavlova a popular and visually appealing dessert.",
    image: "./cakes_img/Pavlova1.jpg",
    image2: "./cakes_img/Pavlova2.jpg",
    recipe_part1: "Crust",
    ingredients_part1: [
      "4 egg whites (size M)",
      "270g sugar",
      "1 teaspoon vanilla paste",
      "7g cornstarch",
    ],
    instructions1:
      "Place the egg whites and sugar in a double boiler and continuously stir (slowly, not vigorously) with a whisk. When the sugar is melted, use a mixer to beat the mixture until it becomes a dense foam that doesn't fall off the mixer paddle. Add the vanilla and cornstarch, then mix for an additional 30 seconds until the mixture is homogeneous. Pour the meringue onto a baking sheet lined with parchment paper and shape it into a round with a diameter of 18cm. Place the tray in a preheated oven at 140°C for 35 minutes (without ventilation, middle rack of the oven). Turn off the oven and let it sit without opening the door for 30 minutes. Afterward, leave the oven door slightly ajar (you can use a wooden spoon to hold it) and let it cool completely (1-2 hours).",
    recipe_part2: "Mascarpone Cream",
    ingredients_part2: [
      "200g mascarpone",
      "150g heavy cream",
      "80g powdered sugar",
    ],
    instructions2:
      "Mix all the ingredients until the cream becomes dense. Spread the cream with gentle movements (do not press too hard to avoid cracking the meringue) and decorate as desired. I recommend using fruits for decoration, as the dessert is slightly sweet, and the combination with tangy fruits is very tasty.",
    observations:
      "With this ingredients you will make a 4 servings Pavlova (maximum 6 people).",
    tipsAndTricks: [
      "If you don't have vanilla paste, replace 10g of the total sugar with a packet of vanilla sugar. If using liquid essences, do not add more than one teaspoon.",
      "If using a hand mixer for beating the meringue, this process takes longer than a stand mixer (at least 10-15 minutes). Patience is crucial. Soft meringue equals a failed Pavlova.",
      "To achieve a more precisely round shape for the Pavlova, a marker and a lid/bottom of a tray can help mark the edges on the parchment paper. If using this method, remember to flip the paper with the drawn side down to avoid the marker's color entering the meringue.",
    ],
  },
  {
    id: "6",
    name: "Medovik with Orange Cream",
    category: "cakes",
    time: "December 17, 2021",
    author: " by Irina Stasii | You Can Bake It!",
    keywords: [
      "cake",
      "medovik cake",
      "honey",
      "sour cream",
      "Orange Cream",
      "orange",
      "christmas",
      "Eggs",
      "Sugar",
      "Baking",
      "Heavy cream",
      "powdered sugar",
      "mascarpone",
      "whipped cream",
    ],
    description:
      "Medovik cake with a delightful twist! This exquisite confection features the classic layers of honey-infused cake, each one tender and rich. What sets it apart is the tantalizing addition of a zesty orange cream layer, adding a burst of citrusy brightness to the traditional Russian honey cake. The medley of sweet honey and vibrant orange creates a harmonious flavor profile that is both indulgent and refreshing, making this Medovik cake with orange cream a truly irresistible treat for your taste buds.",
    image: "./cakes_img/Medovik1.jpg",
    image2: "./cakes_img/Medovik2.jpg",
    recipe_part1: "Honey Layers",
    ingredients_part1: [
      "100g sugar",
      "60g honey",
      "75g butter",
      "1 egg (M)",
      "3g baking soda",
      "3g baking powder",
      "250g flour",
    ],
    instructions1:
      "Caramelize the sugar until it becomes light brown. Add honey, then butter + 3 tablespoons of flour. Add beaten egg. Add baking soda and baking powder. Remove from heat and add flour. Cover with foil and refrigerate for 40 minutes. Bake the layers for 5-10 minutes at 180°C.",
    recipe_part2: "Orange Cream",
    ingredients_part2: [
      "160g orange juice",
      "50g sugar",
      "13g cornstarch",
      "a pinch of salt",
      "2 eggs (M)",
      "100g soft butter, at room temperature",
    ],
    instructions2:
      "Place orange juice and zest in a saucepan. Mix sugar, cornstarch, salt, and eggs; add gradually to the saucepan, stirring constantly. Place the saucepan back on the heat and stir continuously until the mixture thickens. Add 2-4 tablespoons of butter + the optional cognac and let it cool (it should be slightly warm). Whip the remaining butter and add it to the above mixture. Cover with foil and refrigerate. Refrigerate for a minimum of 12 hours. The next day, whip the mixture again before filling the cake.",
    recipe_part3:
      "Cream Cheese/Mascarpone Cream (if choosing to make only ½ of the orange cream)",
    ingredients_part3: [
      "250g mascarpone",
      "80 g whipped cream",
      "40g powdered sugar",
    ],
    instructions3:
      "Mix all the ingredients until you obtain a smooth, dense cream. Spread the layers (one with the orange cream, one with the mascarpone cream). Don't forget to whisk the orange cream when you take it out of the refrigerator.",
    observations:
      "The ingredients are calculated for a cake with a diameter of 18 cm.",
    tipsAndTricks: [
      " To reduce the intensity of the flavor, you can make only half of the orange cream and spread it on one layer, and the next layer with cream cheese/mascarpone. ",
    ],
  },
  {
    id: "7",
    name: "Red Velvet Cake Layers",
    category: "cakes",
    time: "November 14, 2023",
    author: " by Irina Stasii | You Can Bake It!",
    keywords: [
      "cake",
      "cakes",
      "cake layers",
      "red cake",
      "sponge",
      "Eggs",
      "Sugar",
      "Baking",
      "Butter",
      "red velvet",
      "red velvet cake",
      "buttermilk",
      "perfect sponge",
    ],
    description:
      "How many recipes I haven't tested until I found the perfect red velvet cake base. Fluffy, aromatic, doesn't crumble, and most importantly, a distinctive red color. The coloring is crucial when making this cake, i used a water-soluble food coloring. If you're interested in where you could find such a coloring, send me a message, and I will help you.",
    // "Red Velvet Cake with Raspberry Jelly and Mascarpone Cream is a delightful dessert that combines the rich, moist texture of classic red velvet cake with the fruity brightness of raspberry jelly and the luxurious creaminess of mascarpone. The cake's vibrant red color provide a striking contrast to the tartness of the raspberry jelly and the velvety smoothness of the mascarpone cream. Each layer is carefully assembled to create a visually appealing and decadent treat, perfect for special occasions or indulgent moments. The combination of flavors and textures makes this dessert a harmonious blend of sweetness and sophistication, leaving a memorable impression on those fortunate enough to savor its delicious layers.",
    image: "./cakes_img/RV1.jpg",
    // image2: "./cakes_img/RV2.jpg",
    recipe_part1: "2 layers with 20cm diameter",
    ingredients_part1: [
      "300g sugar",
      "120g butter",
      "2 eggs (M)",
      "110g sunflower oil",
      "10g cocoa powder",
      "red food coloring (hidro)",
      "1 teaspoon vanilla paste",
      "a pinch of salt",
      "20g vinegar",
      "350g flour",
      "5g baking soda",
      "250g buttermilk",
    ],
    instructions1:
      "Mix the vinegar, baking soda, and kefir, and let it sit for 10 minutes. Cream the butter with the sugar until it becomes smoother (3-5 minutes). Add one egg at a time, mixing after each addition. Combine oil, cocoa, food coloring, and vanilla, then add to the mixture. Add the rested buttermilk. Add the dry ingredients. Divide the batter into 2 pans with diameter of 20cm (later each will be cut into 2, for a total of 4 layers). Bake at 180°C for 35-40 minutes.",
    //   recipe_part2: "Cream from inside",
    //  ingredients_part2: [
    //    "280g whipped cream",
    //    "200g mascarpone",
    //    "65g powdered sugar"
    //   ],
    //   instructions2:"Mix the mascarpone with the paddle attachment of the mixer (not the whisk attachment). Whip the cream separately with powdered sugar, then combine all the ingredients.",
    //   recipe_part3: "Raspberry jelly",
    //  ingredients_part3: [
    //     "250g thawed raspberries (strained through a sieve, remaining 200)",
    //     "16g cornstarch",
    //     "20g lemon juice",
    //     "50g sugar"
    //   ],
    //   instructions3:"After the raspberries have thawed, strain them through a sieve to remove the seeds. You'll have approximately 200g of raspberries. In a saucepan over high heat, combine all the ingredients and stir continuously. Once it starts boiling, reduce the heat to low and continue stirring until the mixture thickens. Remove from heat, transfer to a bowl, cover with plastic wrap, and cool the mixture in the refrigerator until the next day when we'll assemble the cake.",
    observations:
      // "The ingredients are calculated for a cake with a diameter of 20 cm.",
      "Interested in full recipe? Login and go to courses section from the link below.",
    instaLink: "/cakes",
    tipsAndTricks: "",
  },
  {
    id: "8",
    name: "Cloud Cake",
    category: "cakes",
    time: "February 6, 2021",
    author: " by Irina Stasii | You Can Bake It!",
    keywords: [
      "cake",
      "biscuit cake",
      "cake layers",
      "mascarpone",
      "whipped cream",
      "Chocolate pudding",
      "pudding",
      "cocoa",
      "Baking",
      "Leibniz",
      "milk",
      "biscuits",
      "butter biscuits",
      "cocoa biscuits",
      "perfect sponge",
      "chocolate",
      "milk chocolate",
    ],
    description:
      "It's so simple and easy to make! I didn't expect it to be so delicious. I love the texture of the cake, the subtle cocoa aroma, and the not overly sweet taste. I wholeheartedly recommend it. ",
    image: "./cakes_img/PrajituraRapida1.jpg",
    image2: "./cakes_img/PrajituraRapida2.jpg",
    recipe_part1: "Layers",
    ingredients_part1: [
      "500g mascarpone",
      "200g 35% fat cream for whipped cream",
      "2 packages Chocolate pudding",
      "1 tablespoon cocoa",
      "250g milk",
      "300g Leibniz cocoa biscuits",
      "100g Leibniz butter biscuits",
      "Milk for dipping the biscuits",
    ],
    instructions1:
      "Mix the milk, pudding powder and cocoa with a whisk until the mixture becomes homogeneous and let it sit in the refrigerator for 30 minutes. Whip the mascarpone, whipped cream, and powdered sugar until you get a dense cream. Mix with a whisk the ingredients from point 1 with those from point 2. Dip half of the cocoa biscuits in milk and place a layer on the bottom of the tray. Cover with 1/3 of the total cream quantity. Repeat the same procedure with the butter biscuits, followed by the cocoa ones. So, we'll have a layer of cocoa biscuits - cream - layer of butter biscuits - cream - layer of cocoa biscuits - cream. Simple :) Put the tray in the refrigerator overnight or for at least 10 hours.",
    recipe_part2: "Glaze:",
    ingredients_part2: [
      "150g milk chocolate",
      "100g 35% fat cream for whipped cream ",
    ],
    instructions2:
      "Melt the chocolate with whipped cream over a water bath or in the microwave. Pour over the cake and level it. Let it sit in the refrigerator for at least an hour before portioning.",
    observations: "You must use a tray not larger than 20x25cm or 20x20cm.",
  },
  {
    id: "9",
    name: "Cușma lui Guguță",
    category: "cakes",
    time: "February 23, 2021",
    author: " by Irina Stasii | You Can Bake It!",
    keywords: [
      "cake",
      "guguta",
      "layers",
      "sour cream",
      "cherries compote",
      "cherries",
      "sponge",
      "Eggs",
      "Sugar",
      "Baking",
      "Heavy cream",
      "Butter",
      "cusma lui guguta",
    ],
    description:
      "Cușma lui Guguță is a delightful and visually striking cake originally from Republic of Moldova, known for its unique appearance. The cake is named after the main character in a popular Moldovian children's story. Comprising layers of soft sponge cake, rich whipped cream, and often adorned with chocolate pieces, the Cușma lui Guguță cake resembles a whimsical hat. The layers are carefully stacked to create a distinct cone shape, and the exterior is intricately decorated to mimic the hat made from sheep wool worn by the beloved character. This cake not only captivates with its playful design but also delights the taste buds with its combination of textures and flavors, making it a cherished treat for special occasions and celebrations in Moldovian culture.",
    image: "./cakes_img/Cusma1.jpg",
    image2: "./cakes_img/Cusma2.jpg",
    // video: "https://www.instagram.com/reel/CLwFqgEpyXk/",
    recipe_part1: "Ingredients for rolls:",
    ingredients_part1: [
      "300g soft butter (82% fat)",
      "200g sour cream (25% fat)",
      "500g flour",
      "5g baking soda",
      "one tablespoon vinegar",
      "a jar of 700-800g pitted sour cherries compote ",
    ],
    instructions1:
      "Mix the butter + sour cream + flour to form a dough. Combine the baking soda with vinegar and wait for 10-20 seconds (foam will form). Add it to the dough and knead a bit until well combined. Cover the dough with plastic wrap and leave it in the refrigerator for 30 minutes. Drain the sour cherries well. Take the dough out of the refrigerator and divide it into 4 equal pieces. Take one piece of dough at a time and roll it into a rectangular shape with a rolling pin. Cut it into 4 pieces (strips). Fill each strip of dough with sour cherries and place it on a baking sheet with parchment paper, leaving space between them. I baked 8 rolls/sheet (one sheet in the oven) at 180⁰C for 35 minutes, without ventilation. You'll get a total of 16 rolls. Use 15 for the cake. ",
    recipe_part2: "Cream:",
    ingredients_part2: [
      "700g sour cream (25% fat). Sour cream is crucial here because if it doesn't mix well, the cream will be liquid and will flow.",
      "200g powdered sugar",
      "a packet of vanilla sugar/vanilla paste",
    ],
    instructions2:
      "Mix all the ingredients well until you get a dense, airy cream. Place 5 rolls at the bottom, cover with the cream. The next layer will consist of 4 rolls covered with cream, then 3 - cream - 2 - cream - 1 - cream. This creates the specific shape of this cake. Leave the cake in the refrigerator for a minimum of 10 hours or, preferably, overnight. The cake can also be made with pancakes if you don't have enough time or want to make it quickly, but the taste cannot be compared. 😊 The next day, I decorated the cake with grated chocolate. This is the specific decoration of this cake that represents Guguta's hat.",
    observations:
      " It's the cake of my childhood, and the taste takes me back home. ❤️",
  },
  {
    id: "10",
    name: "Dark Chocolate Truffles",
    category: "",
    time: "August 3, 2020",
    author: " by Irina Stasii | You Can Bake It!",
    keywords: [
      "truffles",
      "chocolate",
      "dark chocolate",
      "heavy cream",
      "whipped cream",
      "cocoa",
    ],
    description:
      "It's not that I don't like dark chocolate. I actually prefer milk chocolate more. However, these truffles, even though they're more bitter, are really good and just melt in your mouth when you eat them. The recipe is simple.",
    image: "./otherRecipesImg/Trufe1.jpg",
    image2: "./otherRecipesImg/Trufe2.jpg",
    recipe_part1: "Ingredients: ",
    ingredients_part1: [
      "300g dark chocolate (up to 70%)",
      "220g (35% fat) heavy cream",
      "cocoa powder (please choose a high quality one)",
    ],
    instructions1:
      "The chocolate and cream are placed in a bowl to melt. They can be melted using two methods: 1. If melting over a double boiler, ensure that the water does not touch the bowl (they melt from the steam). When the water starts to boil, place the bowl over the steam and continuously stir until the mixture is homogeneous. 2.Heat the cream on low heat and when it's close to the boiling point (be careful not to let it boil), remove it from the heat and pour it over the chocolate in the bowl, making sure the cream covers the chocolate. Let it sit for 1 minute without stirring, then mix until the mixture becomes homogeneous. Cover the bowl with parchment paper and place it in the refrigerator for 3-6 hours (depending on the chocolate, the mixture will harden more quickly or slowly). When you feel the mixture is solid enough but not too firm (enough to allow you to form chocolate balls), take it out of the refrigerator and shape it into truffles. Roll the formed truffles in cocoa powder.",
    recipe_part2: "",
    ingredients_part2:"",
    instructions2:"",
    observations: "From this portion, I made approximately 30 truffles.",
    tipsAndTricks: [
      "Chocolate: Look for dark chocolate with a high cocoa content (around 70% or more) for a richer flavor. Brands known for their quality chocolate often mention the cocoa percentage and sometimes even the origin of the beans used.",
      "Cocoa Powder: Choose a good-quality unsweetened cocoa powder for rolling the truffles. Brands that specify 'natural' or 'Dutch-processed' cocoa can offer different flavor profiles, so choose based on your preference.",
    ],
  },
  {
    id: "11",
    name: "Chocolate Brownie",
    category: "",
    time: "August 11, 2020",
    author: " by Irina Stasii | You Can Bake It!",
    keywords: [
      "brownie",
      "chocolate",
      "dark chocolate",
      "brownie cake",
      "chocolate",
      "cocoa",
      "butter",
      "sugar",
      "eggs",
      "flour",
      "cake layer",
      "brownie sponge",
      "sponge" 
    ],
    description:
      "This brownie can be served with ice cream , covered with frosting , or used as a base for a cake . There are many ideas,  and it's very tasty and dense.",
    image: "./otherRecipesImg/Brownie3.jpg",
    image2: "./otherRecipesImg/Brownie1.jpg",
    recipe_part1: "Ingredients: ",
    ingredients_part1: [
      "300g dark chocolate (up to 70%)",
      "185g butter",
      "222g sugar",
      "6 eggs",
      "70g flour",
    ],
    instructions1:
      "Melt the butter together with the chocolate over a double boiler or in the microwave. Add the sugar to the mixture above and stir with a whisk just until they combine. At this point, the bowl is no longer over the double boiler. Add the eggs one at a time, mixing after each addition. Add the flour. Pour the mixture into a baking tray lined with parchment paper greased with butter and place it in a preheated oven at 175°C for 25 minutes.",
    recipe_part2: "",
    ingredients_part2:"",
    instructions2:"",
    observations: "",
    tipsAndTricks: [
      "The brownie should remain slightly moist inside (check with a toothpick after those 25 minutes to see if it's done).",
      "My tray measures 20cm x 30cm. If you have a smaller or larger tray, adjust the quantities by increasing or decreasing the ingredients.",
      "Do not put the tray in the oven until it reaches 175°C.",
    ],
  },
  {
    id: "12",
    name: "Brownie Walnut Cookies",
    category: "cookies",
    time: "September 4, 2020",
    author: " by Irina Stasii | You Can Bake It!",
    keywords: [
      "brownie",
      "chocolate",
      "dark chocolate",
      "brownie cookies",
      "chocolate",
      "walnuts",
      "walnut cookies",
      "cocoa",
      "butter",
      "sugar",
      "eggs",
      "cookies",
      "dark chocolate cookies",
      "fudgy",
      "fudgy cookies"
    ],
    description:
      "Brownie walnut cookies merge the intense, indulgent flavors of a classic brownie with the delightful crunch and nuttiness of walnuts. These cookies boast a rich chocolatey taste, a soft, chewy texture, and the added bonus of wholesome, crunchy walnuts in every bite.",
    image: "./cookies_img/WalnutCookies1.jpg",
    image2: "./cookies_img/WalnutCookies2.jpg",  
    recipe_part1: "Ingredients: ",
    ingredients_part1: [
      "220g dark chocolate (up to 70%)",
      "60g butter min. 80% fat",
      "2 eggs",
      "160g brown sugar",
      "160g flour",
      "5g baking powder",
      "a pinch of salt",
      "25g walnuts",
      "25g heat-resistant chocolate (if you don't have it, you can add what you like: hazelnuts, almonds, raisins, etc.).",
    ],
    instructions1:
      "Melt the chocolate and butter in the microwave or over a double boiler (you can find detailed steps for this in the highlights).Add the flour, baking powder, and salt, combined beforehand. Mix the eggs and brown sugar with a whisk or mixer until they slightly lighten in color and combine with the above mixture, stirring until homogeneous. Add the walnuts and heat-resistant chocolate (you can add here what you prefer: hazelnuts, almonds, raisins, etc.).Add the walnuts and heat-resistant chocolate (you can add here what you prefer: hazelnuts, almonds, raisins, etc.).",
    recipe_part2: "",
    ingredients_part2:"",
    instructions2:"",
    observations: "",
    tipsAndTricks: "",
  },
];
